# ALDEx and variants

ALDEx, ALDEx2 and ALDEx3 share a common philosopy; the count data collected from HTS instruments are a integer-version of a single point estimate of the probability of observing the data. They use multinomial Dirichlet Monte-Carlo sampling to convert the indivitual counts observed into probability distributions that are consistent with the range of probabilities of the data. This approach is necessarily slower, but provides a  posterior estimate of any desired measure. The original ALDEx method provided only effect-size measures as outputs. ALDEx2 incorporated posteriour predicted p-values from t-tests and Wilcoxon tests, by averaging over the probability distribuitons. ALDEx3 brought the full power of linear modelling to the calculation of posterior p-values, included the ability to build scale simulated random variables of the data, all while delivering a massive increase in speed while reducing the comuptational and memory footprint of the approach. 


## Moving from ALDEx2 to ALDEx3

ALDEx2 was developed to provide a semi-Bayesian framework to analyze differential abundance in metatranscriptome datasets (see below). The approach was later shown to be generally useful to analyze essentially all other datasets generated by high throughput sequencing, including transcriptome, microbiome, metagenome and others. When ALDEx2 was included in benchmarking studies it was generally found to have lower false positive rates across multiple datasets regardless of dataset type, this of course came with the caveat or lower sensitivity.  ALDEx2 has two major shortcomings. First, it is slower and uses more memory than most other tools used for differential abundance. Second, it is a relatively inflexible, being most suited to pairwise comparisons of simple experimental designs. The first issue has been addressed through significant optimization of the R code, which resulted in about a 10-fold speedup with somewhat reduced memory useage. The second issue remained unresolved.

Dr. Justin Silverman and his colleagues have recently re-written the code from the ground up and the resulting ALDEx3 R package is available on CRAN. ALDEx3 uses the same Bayesian concepts as ALDEx2 (see below), but is much faster, more memory efficient, and provides many more options for analyzing complex experimental designs. ALDEx3 is based on a linear model framework with significant back-end optimizations. 


# this adds a constant to the TSS scale model
tss.const.sm <- function(X, logComp, const=0, gamma=0.5) {
  P <- nrow(X)
  nsample <- dim(logComp)[3]
  LambdaScale <- matrix(rnorm(P*nsample,const,gamma), P, nsample)
  logScale <- t(X)%*% LambdaScale
  return(logScale)
}

# clr.sm modified to accept a constant for the offset of the estimate
clr.const.sm <- function(X, logComp, const=0, gamma=0.5) {
  P <- nrow(X)
  nsample <- dim(logComp)[3]
  logScale <- -colMeans(logComp, dims=1)

  tmp <- P*nsample
  LambdaScale <- matrix(rnorm(tmp,const,gamma), P, nsample)
  logScale <- logScale + t(X)%*% LambdaScale
  return(logScale)
}

Situation where there is a known relationship between the groups. In the selex dataset, we have a situation where one group is .... This means that the vast majority of the features in each group are at the same relative abundance, and only a few of them increase in absolute and relative abundance. Here the biological interpretation is that the majority of the features should be distributed around an estimate of 0.

An initial analysis using the `tss.sm` shows that the majority of features are centred around -2e8 fold below an estimate of 0. Here is where the `coeffient.sm` is an appropriate choice. 

selex <- read.table('~/Documents/0_git/datasets/selex.txt', header=T, 
	row.names=1, sep='\t')

# estimate G from log2 proportions	
apply(selex+0.5, 2, function(x) mean(log2(x/sum(x))))
# suggests ~2e7 difference in scale between groups

# estimate mean in log2
# equivalent to 1/D
apply(selex+0.5, 2, function(x) log2(mean(x/sum(x))))
# suggests each group has equivalent scale

Y <- selex
conds <- c(rep("N", 7), rep("S",7))
X <- data.frame(conds)

sel.clr <- aldex(Y, ~conds, X, nsample=128, scale=clr.sm, gamma=0)
sel.clr2 <- aldex(Y, ~conds, X, nsample=128, scale=clr.sm, gamma=0)
 sel.coef85 <- aldex(Y, ~conds, X, nsample=128, scale=sample.sm, s.mu=c(rep(-8,7), rep(0,7)), s.var=c(rep(0.5,14)))
 sel.tss85 <- aldex(Y, ~conds, X, nsample=128, scale=const.sm, const=8, gamma=0.5)

sel.coeff <-  aldex(Y, ~conds, X, nsample=128, scale=coefficient.sm, s.mu=c(0,8), s.var=c(0,0.5))
aldex.plot(sel.clr, contrast='conds', plot='effect')
clr.eff <- aldex.effect(sel.clr, contrast='conds')
clr.eff2 <- aldex.effect(sel.clr2, contrast='conds')


sel.tss <- aldex(Y, ~conds, X, nsample=128, scale=const.sm, gamma=0)
tss.eff <- aldex.effect(sel.tss, contrast='conds')

# hist of clr.eff vs tss.eff, suggests modal diff of -8 for tss
# so add const=8 and re-run
sel.tss8 <- aldex(Y, ~conds, X, nsample=128, scale=const.sm, const=8, gamma=0)
sel.tss0 <- aldex(Y, ~conds, X, nsample=128, scale=const.sm, const=0, gamma=0)
tss.eff8 <- aldex.effect(sel.tss8, contrast='conds')
tss.eff0 <- aldex.effect(sel.tss0, contrast='conds')

par(mfrow=c(1,3))
aldex.plot(sel.clr, contrast='conds', main="CLR", plot='eff')
aldex.plot(sel.tss0, contrast='conds', main="TSS, offset=0", plot='eff')
aldex.plot(sel.tss8, contrast='conds', main="TSS, offset=8", plot='eff')

##### ALDEx3 on vaginal dataset
### WARNING: paths in setup.R need changing along with hard-coded paths below
### REQUIRES ALDEx3 which can be obtained from CRAN
library(ALDEx3)

devtools::load_all('~/Documents/0_git/CoDaSeq/CoDaSeq')
path.to.github <- "~/Documents/0_git/projects/dossantos2024study/"

# set path in setup.R to gg
source(paste(path.to.github, "code/setup.R", sep = ""))

# load in vNumber -> KEGG pathway lookup table from VIRGO
path.table <- read.table(paste(locn,'1_VIRGO/8.C.kegg.pathway.copy.txt', sep=""), 
                         sep="\t", header=T, row.names=1, fill=TRUE)

# load in vector containing cst info from london/europe species heatmap
load(paste(path.to.github, 'Rdata/hm.metadata.Rda', sep = ""))

# load in london/europe heatmap column colour bar list
load(paste(path.to.github, "Rdata/hm.column.cols.Rda",sep = ""))

# remove two samples from the filtered london/europe feature table aggregated by
# K0 number (classed as BV but almost no BV organisms):
#   -  v.001A: close to 100% L. gasseri with practically no BV organisms
#   -  v.019A: around 80 % iners, ~ 20% crispatus and a tiny bit of Gardnerella
ko.both<-ko.both[,-c(9,22)]

# remove non-bacterial KOs from the K number-aggregated, filtered feature table
# (these were discovered during curation of 'Unknown' pathways)
#    - K03364: Eukaryotic cell division cycle 20-like protein 1
#    - K13963: Serpin B (eukaryotic serine protease inhibitor)
#    - K01173: Mitochondrial endonuclease G
#    - K12373: Human lysosomal hexosaminidase
#    - K14327: Eukaryotic regulator of nonsense transcripts 2
#    - K00863: Human triose/dihydroxyacetone kinase
#    - K00599: Eukaryotic tRNA N(3)-methylcytidine methyltransferase
#    - K13993: Human HSP20
#    - K00811: Chloroplastic aspartate aminotransferase
#    - K03260: Eukaryotic translation initiation factor 4G
#    - K00985: Enterovirus RNA-directed RNA polymerase

ko.both <- ko.both[-which(grepl(paste("K03364","K13963","K01173","K12373",
                                      "K14327","K00863","K00599","K13993",
                                      "K00811","K03260","K00985", sep = "|"),
                                rownames(ko.both))),]


ko.conds <- c(rep('H',8), rep('B',12), rep('B',14), rep('H', 8)) 

X <- data.frame(ko.conds)

# generate ALDEx3 outputs for plotting
vag.clr <- aldex(ko.both, ~ko.conds, X, nsample=128, scale=clr.sm, gamma=0)
vag.clr5 <- aldex(ko.both, ~ko.conds, X, nsample=128, scale=clr.const.sm, const=-3, gamma=0.5)
vag.tss <- aldex(ko.both, ~ko.conds, X, nsample=128, scale=tss.sm, gamma=0)
vag.tss5 <- aldex(ko.both, ~ko.conds, X, nsample=128, scale=tss.sm, gamma=0.5)

s.mu = c(rep(0,8), rep(0,12), rep(0,14), rep(0, 8))
s.var = c(rep(.5,8), rep(5,12), rep(.5,14), rep(0.5, 8))
vag.samp5 <- aldex(ko.both, ~ko.conds, X, nsample=128, scale=sample.sm, s.mu = s.mu, s.var=s.var)

# shows that tss is the same as clr with offset of -3
par(mfrow=c(2,2))
aldex.plot(vag.clr, contrast='ko.conds', main='clr g=0', plot='eff', cex=0.6)
#abline(h=3, lty=2, col='grey')
aldex.plot(vag.tss, contrast='ko.conds', main='tss g=0', plot='eff', cex=0.6)
aldex.plot(vag.clr5, contrast='ko.conds', main='clr c=-3, g=0.5', plot='eff', cex=0.6)
aldex.plot(vag.tss5, contrast='ko.conds', main='tss g=0.5', plot='eff', cex=0.6)

sum.clr5 <- summary(vag.clr5)
sum.tss5 <- summary(vag.tss5)



